# Site settings
baseURL = "https://nosrob.github.io/"
languageCode = "fr-fr"
title = "Lug"
theme = "lug"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    # Meta
    title = "Lug"
    subtitle = " "
    author = "Nicolas"
    # description = "Our music discoveries"
    # keywords = "Hugo, Blog, Portfolio, Music"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    # buttontext = "Read article"

    # Footer text
    footertext = "🎶"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'