# Site settings
baseURL = "https://nosrob.github.io/"
languageCode = "fr-fr"
title = "Lug"
theme = "lug"

[params]
    title = " "
    subtitle = " "
    author = "Nicalo"
    bodybgcolor = "#f9f9f9"
    footertext = "🎶"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
